---
- include_tasks: shutdown_vm.yml

- name: Delete running VM
  vmware_guest:
    hostname: "{{ vmware_esxi.hostname }}"
    validate_certs: "{{ vmware_esxi.validate_certs }}"
    username: "{{ vmware_esxi.username }}"
    password: "{{ vmware_esxi.password }}"
    datacenter: "{{ vmware_esxi.datacenter }}"
    esxi_hostname: "{{ vmware_esxi.esxi_hostname }}"
    resource_pool: "{{ vmware_esxi.resource_pool }}"
    name: "{{ inventory_hostname }}"
    folder: "{{ inventory_esxi.dest_folder }}"
    state: absent
    force: yes
  delegate_to: localhost
  become: false
