---
# This task list will install a private yum repo and corresponding hosts file
# and make sure prerequisites are met.

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux_disabled

- include_tasks: reboot_linux.yml
  when: selinux_disabled.changed

- name: Setup yum repository definition
  copy:
    src: yum.repo
    dest: /etc/yum.repos.d/yum.repo

- name: Setup the hosts definitions
  copy:
    src: hosts
    dest: /etc/hosts
  become: true

- name: Configure DNS
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- include_tasks: prerequisites.yml

- include_tasks: reboot_linux.yml
